spring.application.name=demo
logging.level.org.springframework.boot.web.embedded.tomcat=DEBUG
logging.level.org.apache.tomcat.util.net=DEBUG
logging.level.org.apache.tomcat.util.net.SSL=DEBUG

# Configurações do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Configurações SSL
server.port=8444
#server.ssl.key-store-type=pfx
#server.ssl.key-store=classpath:certificadofull.pfx
#server.ssl.key-store-password=@Bomfuturo!23@@
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificado.p12
server.ssl.key-store-password=@Bomfuturo!23@@
#server.ssl.key-alias=springboot

# Propriedade customizada para HTTP
custom.server.http.port=8081

#trust store location
#trust.store=classpath:keystore/keystore.p12
#trust store password
#trust.store.password=123456